### ISSUE TITLE
Double definition of `lazymerge`

### ISSUE THREAD

**Issue by theogf** [cscherrer/NestedTuples.jl#16]
https://github.com/cscherrer/NestedTuples.jl/blob/20dfe05ce3ae2ca6e58b88dc83a8dc40d038f0fb/src/lazymerge.jl#L36

is repeated at

https://github.com/cscherrer/NestedTuples.jl/blob/20dfe05ce3ae2ca6e58b88dc83a8dc40d038f0fb/src/lazymerge.jl#L45

**Comment by cscherrer** [comment]
Thanks @theogf . I think we can change the first one to `function lazymerge end`, and just use it for the docs reference. Then `lazymrege` will not always create a `LazyMerge`. For example,
```julia
lazymerge(nt, NamedTuple()) == nt
```
Sometimes we want to be sure to create a LazyMerge (for dispatch, to avoid type piracy for NamedTuples). In those cases we can call `LazyMerge` directly.
